os:
  - linux
  - osx
dist: trusty
language: node_js
node_js:
  - "10"
  - "11"
before_install:
  - npm config set progress=false
script: npm run travis
after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
deploy:
  provider: npm
  on:
    branch: master
  skip_cleanup: true
  email: structuresound@gmail.com
  api_key:
    secure: ilUFg24RiGn5dh5kfbJFcjTqWUMoUIy0NZBxuWG7Thxi6vuAL0ou6NGeh5T9Mbb5eXA50qnd8Fr6QhkEDXLXj+dF2RD2x9iaS4UiilANHtwXNgDo+nzB9A4g3dtu1azBBCJKFTWEIuf1eGGX9ZR7XlEHVLwEcmFoYx0EHIQO1pt0b3AfvDaJVhCpbjNiGZeNLHuw+6gD2TWaxCqwYe45gVZxVAC4HghArHLKMWzSGd+R+buulA3XD2YdW+wo2F5ksdROm9vYMI4ZUppSyPhoHjsp4FBoD69fJzAZ/CmLu9G5xeDbGLev2Bat/LXfPKrAC8OzkD/W+1rg1R9WkSIJOzioTa1rgJOYI0ZydwR8/T3hgAso5x2ci6fG1G2R/T/WVFeZYc9w/VO9zVXEdp1kQGv1tK5BUWDGjprLQHTgT379Cipo2v/6Swn0FNEZpw3XcR4Y5K/NxT9nbHcHfcfjn/lVRFoTK+82zZsfMlqVAFeeO2Dcz1MCbbyqvXT7uBg6BYCb1cxZr5VDIAOLHMNIQWu5ri01DRMxKu4hiejJ1w98tqvjAaxLLvtVR1huhPxV1scc+CBuPE7v2OlAMXy4/0JDiepYvATtr9pC7RTiD4j+UhF1Sa9AKQDvI8NbR9FBzkqhnCbyJAWRnSB7xRIjmMmciev/+ShfTLDBNlzojNU=
